<?php
/**
 * Plugin Name: Youth Apostles Member Directory
 * Description: Interactive, searchable member directory powered by CiviCRM data and React.
 * Version: 0.2.0
 * Author: John Lilly
 * Text Domain: youth-apostles-member-directory
 *
 * ---------------------------------------------------------------------
 * HOW THIS FILE WORKS (for reference, since this is a first plugin):
 *
 * WordPress scans every folder in wp-content/plugins/ looking for a PHP
 * file with a comment block like the one above ("Plugin Name: ..."). It
 * reads that block to know the plugin exists and show it in the Plugins
 * admin screen. Everything below the comment block is just normal PHP
 * that runs whenever WordPress loads.
 * ---------------------------------------------------------------------
 */

// Prevent this file from being loaded directly (only allow it through WP).
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Handy constants so we don't hardcode paths/URLs everywhere.
define( 'YAMD_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'YAMD_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'YAMD_VERSION', '0.2.0' );

// Pull in the class that defines our REST API endpoint.
require_once YAMD_PLUGIN_DIR . 'includes/class-yamd-rest-controller.php';

/**
 * Register our custom REST route(s).
 * `rest_api_init` is the WordPress hook that fires specifically when
 * the REST API is setting itself up — this is the correct place to
 * register custom routes.
 */
add_action(
	'rest_api_init',
	function () {
		$controller = new YAMD_REST_Controller();
		$controller->register_routes();
	}
);

/**
 * Register the [youth_apostles_directory] shortcode.
 * A shortcode is a bit of bracketed text an editor can drop into any
 * WordPress page/post, and WordPress replaces it with whatever our
 * function returns (in this case, an empty <div> that React mounts into).
 */
add_shortcode( 'youth_apostles_directory', 'yamd_render_shortcode' );

function yamd_render_shortcode() {
	yamd_enqueue_assets();
	return '<div id="yamd-directory-root"></div>';
}

/**
 * Enqueue (load) our built React JS/CSS, but only on pages that actually
 * use the shortcode — no point loading it site-wide.
 */
function yamd_enqueue_assets() {
	$asset_file = YAMD_PLUGIN_DIR . 'build/index.asset.php';

	// This file is auto-generated by `npm run build`. If it's missing,
	// the build hasn't been run yet.
	if ( ! file_exists( $asset_file ) ) {
		return;
	}

	// wp-scripts (the build tool) generates a matching .asset.php file
	// that lists the exact WordPress script dependencies (React, etc.)
	// and a version hash, so browsers/WP cache-bust correctly.
	$asset = require $asset_file;

	wp_enqueue_script(
		'yamd-directory-script',
		YAMD_PLUGIN_URL . 'build/index.js',
		$asset['dependencies'],
		$asset['version'],
		true // load in footer
	);

	wp_enqueue_style(
		'yamd-directory-style',
		YAMD_PLUGIN_URL . 'build/style-index.css',
		array(),
		$asset['version']
	);

	/**
	 * Pass data from PHP into JavaScript. This becomes a global JS object
	 * called `yamdData` that our React app reads (window.yamdData.apiUrl, etc).
	 * The nonce is a security token WordPress uses to confirm the request
	 * came from a logged-in session on this site (prevents forged requests).
	 */
	wp_localize_script(
		'yamd-directory-script',
		'yamdData',
		array(
			'apiUrl' => esc_url_raw( rest_url( 'yamd/v1/members' ) ),
			'nonce'  => wp_create_nonce( 'wp_rest' ),
		)
	);
}
